my_robot:
      joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 10  
      
      arm1_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: arm1_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}
